// <copyright file="FeaturesController.cs" company="Engage Software">
// Engage: TellAFriend - http://www.EngageSoftware.com
// Copyright (c) 2004-2010
// by Engage Software ( http://www.engagesoftware.com )
// </copyright>
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED 
// TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF 
// CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
// DEALINGS IN THE SOFTWARE.

namespace Engage.Dnn.TellAFriend
{
    using System.Diagnostics.CodeAnalysis;
    using System.Text.RegularExpressions;

    /// <summary>
    /// Controls which DNN features are available for this module.
    /// </summary>
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1812:AvoidUninstantiatedInternalClasses", Justification = "Instantiated through reflection by DNN")]
    internal class FeaturesController
    {
        /// <summary>
        /// A regular expression which will match an email address
        /// </summary>
        /// <remarks>
        /// Because this needs to work in JavaScript and .NET, we can't just set <see cref="RegexOptions.IgnoreCase"/>, we have to manually include both cases for each letter
        /// <para>Basic Explanation: Any valid characters, @ symbol, any valid characters, . (period), then either two letters or one of the other 25 top-level-domains</para>
        /// <para>
        ///  Beginning of line or string
        ///  Any character in this class: [a-zA-Z0-9._%\-+'], one or more repetitions
        ///  @
        ///  Match expression but don't capture it. [[a-zA-Z0-9\-]+\.], one or more repetitions
        ///      [a-zA-Z0-9\-]+\.
        ///          Any character in this class: [a-zA-Z0-9\-], one or more repetitions
        ///          Literal .
        ///  Match expression but don't capture it. [[a-zA-Z]{2}|[Aa][Ee][Rr][Oo]|[Aa][Rr][Pp][Aa]|[Aa][Ss][Ii][Aa]|[Bb][Ii][Zz]|[Cc][Aa][Tt]|[Cc][Oo][Mm]|[Cc][Oo][Oo][Pp]|[Ee][dD][Uu]|[Gg][Oo][Vv]|[Ii][Nn][Ff][Oo]|[Ii][Nn][Tt]|[Jj][Oo][Bb][Ss]|[Mm][Mm][Ii][Ll]|[Mm][Mm][Oo][Bb][Ii]|[Mm][Uu][Ss][Ee][Uu][Mm]|[Nn][Aa][Mm][Ee]|[Nn][Ee][Tt]|[Oo][Rr][Gg]|[Pp][Rr][Oo]|[Rr][Oo][Oo][Tt]|[Tt][Ee][Ll]|[Tt][Rr][Aa][Vv][Ee][Ll]|[Cc][Yy][Mm]|[Gg][Ee][Oo]|[Pp][Oo][Ss][Tt]]
        ///      Select from 26 alternatives
        ///          Any character in this class: [a-zA-Z], exactly 2 repetitions
        ///          [Aa][Ee][Rr][Oo]
        ///              Any character in this class: [Aa]
        ///              Any character in this class: [Ee]
        ///              Any character in this class: [Rr]
        ///              Any character in this class: [Oo]
        ///          [Aa][Rr][Pp][Aa]
        ///              Any character in this class: [Aa]
        ///              Any character in this class: [Rr]
        ///              Any character in this class: [Pp]
        ///              Any character in this class: [Aa]
        ///          [Aa][Ss][Ii][Aa]
        ///              Any character in this class: [Aa]
        ///              Any character in this class: [Ss]
        ///              Any character in this class: [Ii]
        ///              Any character in this class: [Aa]
        ///          [Bb][Ii][Zz]
        ///              Any character in this class: [Bb]
        ///              Any character in this class: [Ii]
        ///              Any character in this class: [Zz]
        ///          [Cc][Aa][Tt]
        ///              Any character in this class: [Cc]
        ///              Any character in this class: [Aa]
        ///              Any character in this class: [Tt]
        ///          [Cc][Oo][Mm]
        ///              Any character in this class: [Cc]
        ///              Any character in this class: [Oo]
        ///              Any character in this class: [Mm]
        ///          [Cc][Oo][Oo][Pp]
        ///              Any character in this class: [Cc]
        ///              Any character in this class: [Oo]
        ///              Any character in this class: [Oo]
        ///              Any character in this class: [Pp]
        ///          [Ee][dD][Uu]
        ///              Any character in this class: [Ee]
        ///              Any character in this class: [dD]
        ///              Any character in this class: [Uu]
        ///          [Gg][Oo][Vv]
        ///              Any character in this class: [Gg]
        ///              Any character in this class: [Oo]
        ///              Any character in this class: [Vv]
        ///          [Ii][Nn][Ff][Oo]
        ///              Any character in this class: [Ii]
        ///              Any character in this class: [Nn]
        ///              Any character in this class: [Ff]
        ///              Any character in this class: [Oo]
        ///          [Ii][Nn][Tt]
        ///              Any character in this class: [Ii]
        ///              Any character in this class: [Nn]
        ///              Any character in this class: [Tt]
        ///          [Jj][Oo][Bb][Ss]
        ///              Any character in this class: [Jj]
        ///              Any character in this class: [Oo]
        ///              Any character in this class: [Bb]
        ///              Any character in this class: [Ss]
        ///          [Mm][Mm][Ii][Ll]
        ///              Any character in this class: [Mm]
        ///              Any character in this class: [Mm]
        ///              Any character in this class: [Ii]
        ///              Any character in this class: [Ll]
        ///          [Mm][Mm][Oo][Bb][Ii]
        ///              Any character in this class: [Mm]
        ///              Any character in this class: [Mm]
        ///              Any character in this class: [Oo]
        ///              Any character in this class: [Bb]
        ///              Any character in this class: [Ii]
        ///          [Mm][Uu][Ss][Ee][Uu][Mm]
        ///              Any character in this class: [Mm]
        ///              Any character in this class: [Uu]
        ///              Any character in this class: [Ss]
        ///              Any character in this class: [Ee]
        ///              Any character in this class: [Uu]
        ///              Any character in this class: [Mm]
        ///          [Nn][Aa][Mm][Ee]
        ///              Any character in this class: [Nn]
        ///              Any character in this class: [Aa]
        ///              Any character in this class: [Mm]
        ///              Any character in this class: [Ee]
        ///          [Nn][Ee][Tt]
        ///              Any character in this class: [Nn]
        ///              Any character in this class: [Ee]
        ///              Any character in this class: [Tt]
        ///          [Oo][Rr][Gg]
        ///              Any character in this class: [Oo]
        ///              Any character in this class: [Rr]
        ///              Any character in this class: [Gg]
        ///          [Pp][Rr][Oo]
        ///              Any character in this class: [Pp]
        ///              Any character in this class: [Rr]
        ///              Any character in this class: [Oo]
        ///          [Rr][Oo][Oo][Tt]
        ///              Any character in this class: [Rr]
        ///              Any character in this class: [Oo]
        ///              Any character in this class: [Oo]
        ///              Any character in this class: [Tt]
        ///          [Tt][Ee][Ll]
        ///              Any character in this class: [Tt]
        ///              Any character in this class: [Ee]
        ///              Any character in this class: [Ll]
        ///          [Tt][Rr][Aa][Vv][Ee][Ll]
        ///              Any character in this class: [Tt]
        ///              Any character in this class: [Rr]
        ///              Any character in this class: [Aa]
        ///              Any character in this class: [Vv]
        ///              Any character in this class: [Ee]
        ///              Any character in this class: [Ll]
        ///          [Cc][Yy][Mm]
        ///              Any character in this class: [Cc]
        ///              Any character in this class: [Yy]
        ///              Any character in this class: [Mm]
        ///          [Gg][Ee][Oo]
        ///              Any character in this class: [Gg]
        ///              Any character in this class: [Ee]
        ///              Any character in this class: [Oo]
        ///          [Pp][Oo][Ss][Tt]
        ///              Any character in this class: [Pp]
        ///              Any character in this class: [Oo]
        ///              Any character in this class: [Ss]
        ///              Any character in this class: [Tt]
        ///  End of line or string</para>
        /// </remarks>
        [SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", MessageId = "Member", Justification = "Ex is not an acronym.")]
        public const string EmailRegEx = @"^[a-zA-Z0-9._%\-+']+@(?:[a-zA-Z0-9\-]+\.)+(?:[a-zA-Z]{2}|[Aa][Ee][Rr][Oo]|[Aa][Rr][Pp][Aa]|[Aa][Ss][Ii][Aa]|[Bb][Ii][Zz]|[Cc][Aa][Tt]|[Cc][Oo][Mm]|[Cc][Oo][Oo][Pp]|[Ee][dD][Uu]|[Gg][Oo][Vv]|[Ii][Nn][Ff][Oo]|[Ii][Nn][Tt]|[Jj][Oo][Bb][Ss]|[Mm][Ii][Ll]|[Mm][Oo][Bb][Ii]|[Mm][Uu][Ss][Ee][Uu][Mm]|[Nn][Aa][Mm][Ee]|[Nn][Ee][Tt]|[Oo][Rr][Gg]|[Pp][Rr][Oo]|[Rr][Oo][Oo][Tt]|[Tt][Ee][Ll]|[Tt][Rr][Aa][Vv][Ee][Ll]|[Cc][Yy][Mm]|[Gg][Ee][Oo]|[Pp][Oo][Ss][Tt])$";

        /// <summary>
        /// A regular expression which will match a comma-delimited list of email addresses
        /// </summary>
        /// <remarks>
        /// Because this needs to work in JavaScript and .NET, we can't just set <see cref="RegexOptions.IgnoreCase"/>, we have to manually include both cases for each letter
        /// <para>
        /// Basic Explanation: Any valid characters, @ symbol, any valid characters, . (period), then either two letters or one of the other 25 top-level-domains.
        /// Then, any number of times, an optional additional comma, whitespace, and the same pattern as above (that is, another email address)
        /// </para>
        /// <para>
        ///  Beginning of line or string
        ///  Any character in this class: [a-zA-Z0-9._%\-+'], one or more repetitions
        ///  @
        ///  Match expression but don't capture it. [[a-zA-Z0-9\-]+\.], one or more repetitions
        ///      [a-zA-Z0-9\-]+\.
        ///          Any character in this class: [a-zA-Z0-9\-], one or more repetitions
        ///          Literal .
        ///  Match expression but don't capture it. [[a-zA-Z]{2}|[Aa][Ee][Rr][Oo]|[Aa][Rr][Pp][Aa]|[Aa][Ss][Ii][Aa]|[Bb][Ii][Zz]|[Cc][Aa][Tt]|[Cc][Oo][Mm]|[Cc][Oo][Oo][Pp]|[Ee][dD][Uu]|[Gg][Oo][Vv]|[Ii][Nn][Ff][Oo]|[Ii][Nn][Tt]|[Jj][Oo][Bb][Ss]|[Mm][Mm][Ii][Ll]|[Mm][Mm][Oo][Bb][Ii]|[Mm][Uu][Ss][Ee][Uu][Mm]|[Nn][Aa][Mm][Ee]|[Nn][Ee][Tt]|[Oo][Rr][Gg]|[Pp][Rr][Oo]|[Rr][Oo][Oo][Tt]|[Tt][Ee][Ll]|[Tt][Rr][Aa][Vv][Ee][Ll]|[Cc][Yy][Mm]|[Gg][Ee][Oo]|[Pp][Oo][Ss][Tt]]
        ///      Select from 26 alternatives
        ///          Any character in this class: [a-zA-Z], exactly 2 repetitions
        ///          [Aa][Ee][Rr][Oo]
        ///              Any character in this class: [Aa]
        ///              Any character in this class: [Ee]
        ///              Any character in this class: [Rr]
        ///              Any character in this class: [Oo]
        ///          [Aa][Rr][Pp][Aa]
        ///              Any character in this class: [Aa]
        ///              Any character in this class: [Rr]
        ///              Any character in this class: [Pp]
        ///              Any character in this class: [Aa]
        ///          [Aa][Ss][Ii][Aa]
        ///              Any character in this class: [Aa]
        ///              Any character in this class: [Ss]
        ///              Any character in this class: [Ii]
        ///              Any character in this class: [Aa]
        ///          [Bb][Ii][Zz]
        ///              Any character in this class: [Bb]
        ///              Any character in this class: [Ii]
        ///              Any character in this class: [Zz]
        ///          [Cc][Aa][Tt]
        ///              Any character in this class: [Cc]
        ///              Any character in this class: [Aa]
        ///              Any character in this class: [Tt]
        ///          [Cc][Oo][Mm]
        ///              Any character in this class: [Cc]
        ///              Any character in this class: [Oo]
        ///              Any character in this class: [Mm]
        ///          [Cc][Oo][Oo][Pp]
        ///              Any character in this class: [Cc]
        ///              Any character in this class: [Oo]
        ///              Any character in this class: [Oo]
        ///              Any character in this class: [Pp]
        ///          [Ee][dD][Uu]
        ///              Any character in this class: [Ee]
        ///              Any character in this class: [dD]
        ///              Any character in this class: [Uu]
        ///          [Gg][Oo][Vv]
        ///              Any character in this class: [Gg]
        ///              Any character in this class: [Oo]
        ///              Any character in this class: [Vv]
        ///          [Ii][Nn][Ff][Oo]
        ///              Any character in this class: [Ii]
        ///              Any character in this class: [Nn]
        ///              Any character in this class: [Ff]
        ///              Any character in this class: [Oo]
        ///          [Ii][Nn][Tt]
        ///              Any character in this class: [Ii]
        ///              Any character in this class: [Nn]
        ///              Any character in this class: [Tt]
        ///          [Jj][Oo][Bb][Ss]
        ///              Any character in this class: [Jj]
        ///              Any character in this class: [Oo]
        ///              Any character in this class: [Bb]
        ///              Any character in this class: [Ss]
        ///          [Mm][Mm][Ii][Ll]
        ///              Any character in this class: [Mm]
        ///              Any character in this class: [Mm]
        ///              Any character in this class: [Ii]
        ///              Any character in this class: [Ll]
        ///          [Mm][Mm][Oo][Bb][Ii]
        ///              Any character in this class: [Mm]
        ///              Any character in this class: [Mm]
        ///              Any character in this class: [Oo]
        ///              Any character in this class: [Bb]
        ///              Any character in this class: [Ii]
        ///          [Mm][Uu][Ss][Ee][Uu][Mm]
        ///              Any character in this class: [Mm]
        ///              Any character in this class: [Uu]
        ///              Any character in this class: [Ss]
        ///              Any character in this class: [Ee]
        ///              Any character in this class: [Uu]
        ///              Any character in this class: [Mm]
        ///          [Nn][Aa][Mm][Ee]
        ///              Any character in this class: [Nn]
        ///              Any character in this class: [Aa]
        ///              Any character in this class: [Mm]
        ///              Any character in this class: [Ee]
        ///          [Nn][Ee][Tt]
        ///              Any character in this class: [Nn]
        ///              Any character in this class: [Ee]
        ///              Any character in this class: [Tt]
        ///          [Oo][Rr][Gg]
        ///              Any character in this class: [Oo]
        ///              Any character in this class: [Rr]
        ///              Any character in this class: [Gg]
        ///          [Pp][Rr][Oo]
        ///              Any character in this class: [Pp]
        ///              Any character in this class: [Rr]
        ///              Any character in this class: [Oo]
        ///          [Rr][Oo][Oo][Tt]
        ///              Any character in this class: [Rr]
        ///              Any character in this class: [Oo]
        ///              Any character in this class: [Oo]
        ///              Any character in this class: [Tt]
        ///          [Tt][Ee][Ll]
        ///              Any character in this class: [Tt]
        ///              Any character in this class: [Ee]
        ///              Any character in this class: [Ll]
        ///          [Tt][Rr][Aa][Vv][Ee][Ll]
        ///              Any character in this class: [Tt]
        ///              Any character in this class: [Rr]
        ///              Any character in this class: [Aa]
        ///              Any character in this class: [Vv]
        ///              Any character in this class: [Ee]
        ///              Any character in this class: [Ll]
        ///          [Cc][Yy][Mm]
        ///              Any character in this class: [Cc]
        ///              Any character in this class: [Yy]
        ///              Any character in this class: [Mm]
        ///          [Gg][Ee][Oo]
        ///              Any character in this class: [Gg]
        ///              Any character in this class: [Ee]
        ///              Any character in this class: [Oo]
        ///          [Pp][Oo][Ss][Tt]
        ///              Any character in this class: [Pp]
        ///              Any character in this class: [Oo]
        ///              Any character in this class: [Ss]
        ///              Any character in this class: [Tt]
        ///  Match expression but don't capture it. [,\s?[a-zA-Z0-9._%\-+']+@(?:[a-zA-Z0-9\-]+\.)+(?:[a-zA-Z]{2}|[Aa][Ee][Rr][Oo]|[Aa][Rr][Pp][Aa]|[Aa][Ss][Ii][Aa]|[Bb][Ii][Zz]|[Cc][Aa][Tt]|[Cc][Oo][Mm]|[Cc][Oo][Oo][Pp]|[Ee][dD][Uu]|[Gg][Oo][Vv]|[Ii][Nn][Ff][Oo]|[Ii][Nn][Tt]|[Jj][Oo][Bb][Ss]|[Mm][Mm][Ii][Ll]|[Mm][Mm][Oo][Bb][Ii]|[Mm][Uu][Ss][Ee][Uu][Mm]|[Nn][Aa][Mm][Ee]|[Nn][Ee][Tt]|[Oo][Rr][Gg]|[Pp][Rr][Oo]|[Rr][Oo][Oo][Tt]|[Tt][Ee][Ll]|[Tt][Rr][Aa][Vv][Ee][Ll]|[Cc][Yy][Mm]|[Gg][Ee][Oo]|[Pp][Oo][Ss][Tt])], any number of repetitions
        ///      ,\s?[a-zA-Z0-9._%\-+']+@(?:[a-zA-Z0-9\-]+\.)+(?:[a-zA-Z]{2}|[Aa][Ee][Rr][Oo]|[Aa][Rr][Pp][Aa]|[Aa][Ss][Ii][Aa]|[Bb][Ii][Zz]|[Cc][Aa][Tt]|[Cc][Oo][Mm]|[Cc][Oo][Oo][Pp]|[Ee][dD][Uu]|[Gg][Oo][Vv]|[Ii][Nn][Ff][Oo]|[Ii][Nn][Tt]|[Jj][Oo][Bb][Ss]|[Mm][Mm][Ii][Ll]|[Mm][Mm][Oo][Bb][Ii]|[Mm][Uu][Ss][Ee][Uu][Mm]|[Nn][Aa][Mm][Ee]|[Nn][Ee][Tt]|[Oo][Rr][Gg]|[Pp][Rr][Oo]|[Rr][Oo][Oo][Tt]|[Tt][Ee][Ll]|[Tt][Rr][Aa][Vv][Ee][Ll]|[Cc][Yy][Mm]|[Gg][Ee][Oo]|[Pp][Oo][Ss][Tt])
        ///          ,
        ///          Whitespace, zero or one repetitions
        ///          Any character in this class: [a-zA-Z0-9._%\-+'], one or more repetitions
        ///          @
        ///          Match expression but don't capture it. [[a-zA-Z0-9\-]+\.], one or more repetitions
        ///              [a-zA-Z0-9\-]+\.
        ///                  Any character in this class: [a-zA-Z0-9\-], one or more repetitions
        ///                  Literal .
        ///          Match expression but don't capture it. [[a-zA-Z]{2}|[Aa][Ee][Rr][Oo]|[Aa][Rr][Pp][Aa]|[Aa][Ss][Ii][Aa]|[Bb][Ii][Zz]|[Cc][Aa][Tt]|[Cc][Oo][Mm]|[Cc][Oo][Oo][Pp]|[Ee][dD][Uu]|[Gg][Oo][Vv]|[Ii][Nn][Ff][Oo]|[Ii][Nn][Tt]|[Jj][Oo][Bb][Ss]|[Mm][Mm][Ii][Ll]|[Mm][Mm][Oo][Bb][Ii]|[Mm][Uu][Ss][Ee][Uu][Mm]|[Nn][Aa][Mm][Ee]|[Nn][Ee][Tt]|[Oo][Rr][Gg]|[Pp][Rr][Oo]|[Rr][Oo][Oo][Tt]|[Tt][Ee][Ll]|[Tt][Rr][Aa][Vv][Ee][Ll]|[Cc][Yy][Mm]|[Gg][Ee][Oo]|[Pp][Oo][Ss][Tt]]
        ///              Select from 26 alternatives
        ///                  Any character in this class: [a-zA-Z], exactly 2 repetitions
        ///                  [Aa][Ee][Rr][Oo]
        ///                      Any character in this class: [Aa]
        ///                      Any character in this class: [Ee]
        ///                      Any character in this class: [Rr]
        ///                      Any character in this class: [Oo]
        ///                  [Aa][Rr][Pp][Aa]
        ///                      Any character in this class: [Aa]
        ///                      Any character in this class: [Rr]
        ///                      Any character in this class: [Pp]
        ///                      Any character in this class: [Aa]
        ///                  [Aa][Ss][Ii][Aa]
        ///                      Any character in this class: [Aa]
        ///                      Any character in this class: [Ss]
        ///                      Any character in this class: [Ii]
        ///                      Any character in this class: [Aa]
        ///                  [Bb][Ii][Zz]
        ///                      Any character in this class: [Bb]
        ///                      Any character in this class: [Ii]
        ///                      Any character in this class: [Zz]
        ///                  [Cc][Aa][Tt]
        ///                      Any character in this class: [Cc]
        ///                      Any character in this class: [Aa]
        ///                      Any character in this class: [Tt]
        ///                  [Cc][Oo][Mm]
        ///                      Any character in this class: [Cc]
        ///                      Any character in this class: [Oo]
        ///                      Any character in this class: [Mm]
        ///                  [Cc][Oo][Oo][Pp]
        ///                      Any character in this class: [Cc]
        ///                      Any character in this class: [Oo]
        ///                      Any character in this class: [Oo]
        ///                      Any character in this class: [Pp]
        ///                  [Ee][dD][Uu]
        ///                      Any character in this class: [Ee]
        ///                      Any character in this class: [dD]
        ///                      Any character in this class: [Uu]
        ///                  [Gg][Oo][Vv]
        ///                      Any character in this class: [Gg]
        ///                      Any character in this class: [Oo]
        ///                      Any character in this class: [Vv]
        ///                  [Ii][Nn][Ff][Oo]
        ///                      Any character in this class: [Ii]
        ///                      Any character in this class: [Nn]
        ///                      Any character in this class: [Ff]
        ///                      Any character in this class: [Oo]
        ///                  [Ii][Nn][Tt]
        ///                      Any character in this class: [Ii]
        ///                      Any character in this class: [Nn]
        ///                      Any character in this class: [Tt]
        ///                  [Jj][Oo][Bb][Ss]
        ///                      Any character in this class: [Jj]
        ///                      Any character in this class: [Oo]
        ///                      Any character in this class: [Bb]
        ///                      Any character in this class: [Ss]
        ///                  [Mm][Mm][Ii][Ll]
        ///                      Any character in this class: [Mm]
        ///                      Any character in this class: [Mm]
        ///                      Any character in this class: [Ii]
        ///                      Any character in this class: [Ll]
        ///                  [Mm][Mm][Oo][Bb][Ii]
        ///                      Any character in this class: [Mm]
        ///                      Any character in this class: [Mm]
        ///                      Any character in this class: [Oo]
        ///                      Any character in this class: [Bb]
        ///                      Any character in this class: [Ii]
        ///                  [Mm][Uu][Ss][Ee][Uu][Mm]
        ///                      Any character in this class: [Mm]
        ///                      Any character in this class: [Uu]
        ///                      Any character in this class: [Ss]
        ///                      Any character in this class: [Ee]
        ///                      Any character in this class: [Uu]
        ///                      Any character in this class: [Mm]
        ///                  [Nn][Aa][Mm][Ee]
        ///                      Any character in this class: [Nn]
        ///                      Any character in this class: [Aa]
        ///                      Any character in this class: [Mm]
        ///                      Any character in this class: [Ee]
        ///                  [Nn][Ee][Tt]
        ///                      Any character in this class: [Nn]
        ///                      Any character in this class: [Ee]
        ///                      Any character in this class: [Tt]
        ///                  [Oo][Rr][Gg]
        ///                      Any character in this class: [Oo]
        ///                      Any character in this class: [Rr]
        ///                      Any character in this class: [Gg]
        ///                  [Pp][Rr][Oo]
        ///                      Any character in this class: [Pp]
        ///                      Any character in this class: [Rr]
        ///                      Any character in this class: [Oo]
        ///                  [Rr][Oo][Oo][Tt]
        ///                      Any character in this class: [Rr]
        ///                      Any character in this class: [Oo]
        ///                      Any character in this class: [Oo]
        ///                      Any character in this class: [Tt]
        ///                  [Tt][Ee][Ll]
        ///                      Any character in this class: [Tt]
        ///                      Any character in this class: [Ee]
        ///                      Any character in this class: [Ll]
        ///                  [Tt][Rr][Aa][Vv][Ee][Ll]
        ///                      Any character in this class: [Tt]
        ///                      Any character in this class: [Rr]
        ///                      Any character in this class: [Aa]
        ///                      Any character in this class: [Vv]
        ///                      Any character in this class: [Ee]
        ///                      Any character in this class: [Ll]
        ///                  [Cc][Yy][Mm]
        ///                      Any character in this class: [Cc]
        ///                      Any character in this class: [Yy]
        ///                      Any character in this class: [Mm]
        ///                  [Gg][Ee][Oo]
        ///                      Any character in this class: [Gg]
        ///                      Any character in this class: [Ee]
        ///                      Any character in this class: [Oo]
        ///                  [Pp][Oo][Ss][Tt]
        ///                      Any character in this class: [Pp]
        ///                      Any character in this class: [Oo]
        ///                      Any character in this class: [Ss]
        ///                      Any character in this class: [Tt]
        ///  End of line or string</para>
        /// </remarks>
        [SuppressMessage("Microsoft.Naming", "CA1706:ShortAcronymsShouldBeUppercase", MessageId = "Member", Justification = "Ex is not an acronym.")]
        public const string EmailsRegEx = @"^[a-zA-Z0-9._%\-+']+@(?:[a-zA-Z0-9\-]+\.)+(?:[a-zA-Z]{2}|[Aa][Ee][Rr][Oo]|[Aa][Rr][Pp][Aa]|[Aa][Ss][Ii][Aa]|[Bb][Ii][Zz]|[Cc][Aa][Tt]|[Cc][Oo][Mm]|[Cc][Oo][Oo][Pp]|[Ee][dD][Uu]|[Gg][Oo][Vv]|[Ii][Nn][Ff][Oo]|[Ii][Nn][Tt]|[Jj][Oo][Bb][Ss]|[Mm][Mm][Ii][Ll]|[Mm][Mm][Oo][Bb][Ii]|[Mm][Uu][Ss][Ee][Uu][Mm]|[Nn][Aa][Mm][Ee]|[Nn][Ee][Tt]|[Oo][Rr][Gg]|[Pp][Rr][Oo]|[Rr][Oo][Oo][Tt]|[Tt][Ee][Ll]|[Tt][Rr][Aa][Vv][Ee][Ll]|[Cc][Yy][Mm]|[Gg][Ee][Oo]|[Pp][Oo][Ss][Tt])(?:,\s?[a-zA-Z0-9._%\-+']+@(?:[a-zA-Z0-9\-]+\.)+(?:[a-zA-Z]{2}|[Aa][Ee][Rr][Oo]|[Aa][Rr][Pp][Aa]|[Aa][Ss][Ii][Aa]|[Bb][Ii][Zz]|[Cc][Aa][Tt]|[Cc][Oo][Mm]|[Cc][Oo][Oo][Pp]|[Ee][dD][Uu]|[Gg][Oo][Vv]|[Ii][Nn][Ff][Oo]|[Ii][Nn][Tt]|[Jj][Oo][Bb][Ss]|[Mm][Mm][Ii][Ll]|[Mm][Mm][Oo][Bb][Ii]|[Mm][Uu][Ss][Ee][Uu][Mm]|[Nn][Aa][Mm][Ee]|[Nn][Ee][Tt]|[Oo][Rr][Gg]|[Pp][Rr][Oo]|[Rr][Oo][Oo][Tt]|[Tt][Ee][Ll]|[Tt][Rr][Aa][Vv][Ee][Ll]|[Cc][Yy][Mm]|[Gg][Ee][Oo]|[Pp][Oo][Ss][Tt]))*$";
    }
}